use std::{
    env,
    sync::{
        Arc, Mutex,
        atomic::{AtomicBool, Ordering},
    },
};

use tracing::{debug, info, warn};

use crate::{
    devices::{
        errors::{
            CloseError, FindError, InfoError, OpenError, StateError, SubmissionError,
        },
        format::{BufferSize, ChannelSpec, FormatInfo, SampleFormat},
        traits::{Device, DeviceProvider, OutputStream},
    },
    media::pipeline::ChannelConsumers,
};

pub type CapturedPlanes = Arc<Mutex<Vec<Vec<f64>>>>;

static CAPTURE: Mutex<Option<CapturedPlanes>> = Mutex::new(None);

/// Install a sink that records every sample reaching the dummy device layer. Used by tests to
/// capture the end result of the pipeline.
#[cfg_attr(not(test), allow(dead_code))]
pub fn install_capture() -> CapturedPlanes {
    let sink: CapturedPlanes = Arc::new(Mutex::new(Vec::new()));
    *CAPTURE.lock().unwrap() = Some(Arc::clone(&sink));
    sink
}

/// Remove the sink installed by [`install_capture`], if any.
#[cfg_attr(not(test), allow(dead_code))]
pub fn uninstall_capture() {
    *CAPTURE.lock().unwrap() = None;
}

/// Set once a modelled device death has fired, so the recreated stream doesn't die again.
static DEVICE_ALREADY_DIED: AtomicBool = AtomicBool::new(false);

/// Reset the one-shot latch so the next stream to reach `HB_DUMMY_DIE_AFTER_FRAMES` faults once.
#[cfg_attr(not(test), allow(dead_code))]
pub fn arm_device_death() {
    DEVICE_ALREADY_DIED.store(false, Ordering::SeqCst);
}

fn capture_samples<T: Copy + Into<f64>>(staging: &[Vec<T>], read: usize) {
    let guard = CAPTURE.lock().unwrap();
    let Some(sink) = guard.as_ref() else { return };

    let mut planes = sink.lock().unwrap();
    if planes.len() < staging.len() {
        planes.resize_with(staging.len(), Vec::new);
    }
    for (plane, channel) in planes.iter_mut().zip(staging) {
        plane.extend(channel[..read].iter().map(|&sample| sample.into()));
    }
}

/// The dummy device provider is provided for testing purposes. It does not play any actual audio,
/// and submitting samples to devices generated by this provider is a no-op.
///
/// This streams provided by this device provider will never block when samples are submitted,
/// meaning that the playback thread will likely submit the next samples immediately.
///
/// The following environment variables can be used to configure the dummy device:
/// - `HB_DUMMY_SAMPLE_RATE`: The sample rate of the dummy device. Defaults to 44100.
/// - `HB_DUMMY_BIT_FORMAT`: The bit format of the dummy device. Defaults to `S16`.
/// - `HB_DUMMY_CHANNELS`: The number of channels of the dummy device. Defaults to 2.
/// - `HB_DUMMY_BUFFER_SIZE`: The buffer size of the dummy device. Defaults to 4096.
///   - This doesn't actually do anything: no samples are ever loaded into a buffer.
pub struct DummyDeviceProvider {}

impl DummyDeviceProvider {
    pub fn new() -> Self {
        Self {}
    }
}

impl DeviceProvider for DummyDeviceProvider {
    fn initialize(&mut self) {
        info!("DummyDeviceProvider initialized");
        warn!("This device provider WILL not play any actual audio.");
    }

    fn get_default_device(&mut self) -> Result<Box<dyn Device>, FindError> {
        debug!("Creating new dummy device");
        Ok(Box::new(DummyDevice {}) as Box<dyn Device>)
    }
}

pub struct DummyDevice {}

impl DummyDevice {
    pub fn get_sample_rate() -> u32 {
        env::var("HB_DUMMY_SAMPLE_RATE")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(44100)
    }

    pub fn get_bit_format() -> Result<SampleFormat, InfoError> {
        let var = env::var("HB_DUMMY_BIT_FORMAT");
        Ok(match var.as_deref() {
            Ok("F64") => SampleFormat::Float64,
            Ok("F32") => SampleFormat::Float32,
            Ok("S32") => SampleFormat::Signed32,
            Ok("U32") => SampleFormat::Unsigned32,
            Ok("S24") => SampleFormat::Signed24,
            Ok("U24") => SampleFormat::Unsigned24,
            Ok("S16") => SampleFormat::Signed16,
            Ok("U16") => SampleFormat::Unsigned16,
            Ok("S8") => SampleFormat::Signed8,
            Ok("U8") => SampleFormat::Unsigned8,
            Err(std::env::VarError::NotPresent) => SampleFormat::Signed16,
            Ok(_) => Err(InfoError::SampleFmt(var.unwrap()))?,
            Err(std::env::VarError::NotUnicode(os)) => {
                Err(InfoError::SampleFmt(os.to_string_lossy().into_owned()))?
            }
        })
    }

    pub fn get_channels() -> u16 {
        env::var("HB_DUMMY_CHANNELS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(2)
    }

    pub fn get_buffer_size() -> u32 {
        env::var("HB_DUMMY_BUFFER_SIZE")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(4096)
    }

    pub fn get_bounded_frames() -> Option<usize> {
        env::var("HB_DUMMY_BOUNDED_FRAMES")
            .ok()
            .and_then(|s| s.parse().ok())
    }

    pub fn get_drain_frames() -> usize {
        env::var("HB_DUMMY_DRAIN_FRAMES")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(1024)
    }

    pub fn get_die_after_frames() -> Option<usize> {
        env::var("HB_DUMMY_DIE_AFTER_FRAMES")
            .ok()
            .and_then(|s| s.parse().ok())
    }
}

impl Device for DummyDevice {
    fn open_device(&mut self, _format: FormatInfo) -> Result<Box<dyn OutputStream>, OpenError> {
        if let Some(capacity) = DummyDevice::get_bounded_frames() {
            let drain = DummyDevice::get_drain_frames();
            return Ok(Box::new(BoundedDummyStream::new(capacity, drain)) as Box<dyn OutputStream>);
        }
        let device = DummyStream {
            die_after: DummyDevice::get_die_after_frames(),
            consumed: 0,
        };
        Ok(Box::new(device) as Box<dyn OutputStream>)
    }

    fn get_default_format(&self) -> Result<FormatInfo, InfoError> {
        Ok(FormatInfo {
            originating_provider: "dummy",
            sample_type: DummyDevice::get_bit_format()?,
            sample_rate: DummyDevice::get_sample_rate(),
            buffer_size: BufferSize::Fixed(DummyDevice::get_buffer_size()),
            channels: ChannelSpec::Count(DummyDevice::get_channels()),
        })
    }

    fn get_name(&self) -> Result<String, InfoError> {
        Ok("Meliora Dummy Audio Device".to_string())
    }


}

pub struct DummyStream {
    /// If set, fault once after this many consumed frames (see [`arm_device_death`]).
    die_after: Option<usize>,
    consumed: usize,
}

impl DummyStream {
    /// True (consuming the one-shot latch) if this stream should fault now.
    fn should_die(&self) -> bool {
        match self.die_after {
            Some(threshold) if self.consumed >= threshold => DEVICE_ALREADY_DIED
                .compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst)
                .is_ok(),
            _ => false,
        }
    }
}

impl OutputStream for DummyStream {
    fn close_stream(&mut self) -> Result<(), CloseError> {
        debug!("Stream closed.");
        Ok(())
    }

    fn play(&mut self) -> Result<(), StateError> {
        debug!("Stream resumed.");
        Ok(())
    }

    fn pause(&mut self) -> Result<(), StateError> {
        debug!("Stream paused.");
        Ok(())
    }

    fn reset(&mut self) -> Result<(), crate::devices::errors::ResetError> {
        debug!("Stream reset.");
        Ok(())
    }

    fn set_volume(&mut self, volume: f64) -> Result<(), StateError> {
        debug!("Volume set to {}.", volume);
        Ok(())
    }

    fn consume_from(
        &mut self,
        input: &mut ChannelConsumers,
    ) -> Result<usize, SubmissionError> {
        // fault before reading so no frames are lost
        if self.should_die() {
            return Err(SubmissionError::DeviceError);
        }

        let available = input.potentially_available();
        if available == 0 {
            return Ok(0);
        }

        // Just drain the samples without doing anything with them
        let read = input.try_read_to_staging(available);
        capture_samples(input.staging(), read);
        self.consumed += read;
        debug!("Consumed {} samples from ring buffer (dummy device)", read);
        Ok(read)
    }
}

/// A dummy stream that models a real device's bounded hardware ring: it holds at most `capacity`
/// frames and "plays" `drain` of them per `consume_from` call (advancing playback), so it only
/// accepts as much new input as it has free space. Used to test for specific bugs that only occur
/// under back-pressure.
pub struct BoundedDummyStream {
    capacity: usize,
    drain: usize,
    /// Frames currently buffered in the modelled hardware ring.
    fill: usize,
}

impl BoundedDummyStream {
    fn new(capacity: usize, drain: usize) -> Self {
        Self {
            capacity,
            drain: drain.max(1),
            fill: 0,
        }
    }
}

impl OutputStream for BoundedDummyStream {
    fn close_stream(&mut self) -> Result<(), CloseError> {
        Ok(())
    }

    fn play(&mut self) -> Result<(), StateError> {
        Ok(())
    }

    fn pause(&mut self) -> Result<(), StateError> {
        Ok(())
    }

    fn reset(&mut self) -> Result<(), crate::devices::errors::ResetError> {
        self.fill = 0;
        Ok(())
    }

    fn set_volume(&mut self, _volume: f64) -> Result<(), StateError> {
        Ok(())
    }

    fn consume_from(
        &mut self,
        input: &mut ChannelConsumers,
    ) -> Result<usize, SubmissionError> {
        // advance playback: drain up to `drain` frames from the ring
        self.fill = self.fill.saturating_sub(self.drain);

        let free = self.capacity - self.fill;
        let available = input.potentially_available().min(free);
        if available == 0 {
            return Ok(0);
        }

        let read = input.try_read_to_staging(available);
        capture_samples(input.staging(), read);
        self.fill += read;
        Ok(read)
    }
}
