//! Request signing schemes, mirroring `KuGouMusicApi/util/helper.js`.
//!
//! All variants boil down to "salt + sorted params + salt" fed to MD5.

use std::collections::BTreeMap;

use super::crypto::md5_hex;

const ANDROID_SALT: &str = "LnT6xpN3khm36zse0QzvmgTZ3waWdRSA";
const WEB_SALT: &str = "NVPh5oo715z5DIWAeQlhMDsWXXQV4hwt";
const KEY_SALT: &str = "185672dd44712f60bb1736df5a377e82";

fn sorted_param_string(params: &BTreeMap<String, String>) -> String {
    // BTreeMap already keeps keys sorted lexicographically, matching the
    // JS Object.keys(...).sort() used by the reference client.
    let mut out = String::new();
    for (key, value) in params {
        out.push_str(key);
        out.push('=');
        out.push_str(value);
    }
    out
}

/// `signatureAndroidParams`: salt + params + body + salt.
pub fn signature_android(params: &BTreeMap<String, String>, body: &str) -> String {
    md5_hex(&format!(
        "{ANDROID_SALT}{}{body}{ANDROID_SALT}",
        sorted_param_string(params)
    ))
}

/// `signatureWebParams`: salt + params + salt (no body).
pub fn signature_web(params: &BTreeMap<String, String>) -> String {
    md5_hex(&format!(
        "{WEB_SALT}{}{WEB_SALT}",
        sorted_param_string(params)
    ))
}

/// `signKey`: MD5(hash + salt + appid + mid + userid), used by /v5/url.
pub fn sign_key(hash: &str, mid: &str, userid: &str, appid: &str) -> String {
    md5_hex(&format!("{hash}{KEY_SALT}{appid}{mid}{userid}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn params() -> BTreeMap<String, String> {
        let mut p = BTreeMap::new();
        p.insert("clienttime".to_string(), "1700000000".to_string());
        p.insert("appid".to_string(), "1005".to_string());
        p.insert("mid".to_string(), "123456789".to_string());
        p
    }

    /// Reference vectors generated by running the original
    /// KuGouMusicApi/util/helper.js under node — the exact digests the real
    /// client produces for these inputs (including a UTF-8 keyword).
    fn reference_params() -> BTreeMap<String, String> {
        let mut p = BTreeMap::new();
        p.insert("appid".to_string(), "1005".to_string());
        p.insert("clienttime".to_string(), "1700000000".to_string());
        p.insert(
            "mid".to_string(),
            "12345678901234567890123456789012".to_string(),
        );
        p.insert("dfid".to_string(), "testdfid".to_string());
        p.insert("keyword".to_string(), "周杰伦".to_string());
        p.insert("uuid".to_string(), "-".to_string());
        p
    }

    #[test]
    fn android_signature_is_stable_md5() {
        let sig = signature_android(&params(), "");
        assert_eq!(sig.len(), 32);
        assert!(sig.chars().all(|c| c.is_ascii_hexdigit()));
        // body participates in the digest
        assert_ne!(sig, signature_android(&params(), "body"));
    }

    #[test]
    fn signatures_match_the_javascript_client() {
        let params = reference_params();
        assert_eq!(
            signature_android(&params, ""),
            "3760e0a93f2a4eef48e879beac48a6cc"
        );
        assert_eq!(
            signature_web(&params),
            "40fb8f10e2077f582ecf350ed6838b99"
        );
        assert_eq!(
            sign_key(
                "ABCDEF1234",
                "12345678901234567890123456789012",
                "7749",
                "1005"
            ),
            "8f6f15f3c88a5d9fe510c9411c499939"
        );
    }

    #[test]
    fn web_signature_differs_from_android() {
        assert_ne!(signature_web(&params()), signature_android(&params(), ""));
    }

    #[test]
    fn sign_key_composes_expected_string() {
        assert_eq!(
            sign_key("hash", "mid", "7", "1005"),
            md5_hex(&format!("hash{KEY_SALT}1005mid7"))
        );
    }
}
