//! Request signing schemes, mirroring `KuGouMusicApi/util/helper.js`.
//!
//! All variants boil down to "salt + sorted params + salt" fed to MD5.
//!
//! Upstream picks the salt per client variant: the lite (概念版) client uses
//! `LnT6xpN3khm36zse0QzvmgTZ3waWdRSA` / `185672dd44712f60bb1736df5a377e82`,
//! the standard client `OIlwieks28dk2k092lksi2UIkp` /
//! `57ae12eb6890223e355ccfcb74edf70d`. Meliora emulates the lite client
//! (appid 3116, mid derived from dfid), so the lite salts are hardcoded here.

use std::collections::BTreeMap;

use super::crypto::md5_hex;

/// Lite-client Android request salt (`signatureAndroidParams` with
/// `platform=lite`).
const ANDROID_SALT: &str = "LnT6xpN3khm36zse0QzvmgTZ3waWdRSA";
const WEB_SALT: &str = "NVPh5oo715z5DIWAeQlhMDsWXXQV4hwt";
/// Lite-client request key salt (`signKey` with `platform=lite`).
const KEY_SALT: &str = "185672dd44712f60bb1736df5a377e82";

fn sorted_param_string(params: &BTreeMap<String, String>) -> String {
    // BTreeMap already keeps keys sorted lexicographically, matching the
    // JS Object.keys(...).sort() used by the reference client.
    let mut out = String::new();
    for (key, value) in params {
        out.push_str(key);
        out.push('=');
        out.push_str(value);
    }
    out
}

/// `signatureAndroidParams`: salt + params + body + salt.
pub fn signature_android(params: &BTreeMap<String, String>, body: &str) -> String {
    md5_hex(&format!(
        "{ANDROID_SALT}{}{body}{ANDROID_SALT}",
        sorted_param_string(params)
    ))
}

/// `signatureWebParams`: salt + params + salt (no body).
pub fn signature_web(params: &BTreeMap<String, String>) -> String {
    md5_hex(&format!(
        "{WEB_SALT}{}{WEB_SALT}",
        sorted_param_string(params)
    ))
}

/// `signKey`: MD5(hash + salt + appid + mid + userid), used by /v5/url.
pub fn sign_key(hash: &str, mid: &str, userid: &str, appid: &str) -> String {
    md5_hex(&format!("{hash}{KEY_SALT}{appid}{mid}{userid}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn params() -> BTreeMap<String, String> {
        let mut p = BTreeMap::new();
        p.insert("clienttime".to_string(), "1700000000".to_string());
        p.insert("appid".to_string(), "1005".to_string());
        p.insert("mid".to_string(), "123456789".to_string());
        p
    }

    /// Reference vectors generated by running the original
    /// KuGouMusicApi/util/helper.js under node with `platform=lite` — the
    /// exact digests the lite client (which Meliora emulates) produces for
    /// these inputs (including a UTF-8 keyword). The standard-variant salts
    /// (`OIlwieks28dk2k092lksi2UIkp` for requests, `57ae12eb6890223e355ccfcb74edf70d`
    /// for signKey) yield `3760e0a93f2a4eef48e879beac48a6cc` and
    /// `8f6f15f3c88a5d9fe510c9411c499939` instead — do not mix the two up.
    fn reference_params() -> BTreeMap<String, String> {
        let mut p = BTreeMap::new();
        p.insert("appid".to_string(), "1005".to_string());
        p.insert("clienttime".to_string(), "1700000000".to_string());
        p.insert(
            "mid".to_string(),
            "12345678901234567890123456789012".to_string(),
        );
        p.insert("dfid".to_string(), "testdfid".to_string());
        p.insert("keyword".to_string(), "周杰伦".to_string());
        p.insert("uuid".to_string(), "-".to_string());
        p
    }

    #[test]
    fn android_signature_is_stable_md5() {
        let sig = signature_android(&params(), "");
        assert_eq!(sig.len(), 32);
        assert!(sig.chars().all(|c| c.is_ascii_hexdigit()));
        // body participates in the digest
        assert_ne!(sig, signature_android(&params(), "body"));
    }

    #[test]
    fn signatures_match_the_javascript_client() {
        let params = reference_params();
        // lite-client vectors (node, platform=lite); the implementation and
        // the production client are the lite variant, see module docs above
        assert_eq!(
            signature_android(&params, ""),
            "b393d0a09117e5ea0366421a501b197f"
        );
        assert_eq!(signature_web(&params), "40fb8f10e2077f582ecf350ed6838b99");
        assert_eq!(
            sign_key(
                "ABCDEF1234",
                "12345678901234567890123456789012",
                "7749",
                "1005"
            ),
            "5c041d62b8491c4c4f107a8de47713da"
        );
    }

    #[test]
    fn web_signature_differs_from_android() {
        assert_ne!(signature_web(&params()), signature_android(&params(), ""));
    }

    #[test]
    fn sign_key_composes_expected_string() {
        assert_eq!(
            sign_key("hash", "mid", "7", "1005"),
            md5_hex(&format!("hash{KEY_SALT}1005mid7"))
        );
    }
}
